# Generated by Django 4.1.7 on 2023-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_mobile", models.CharField(max_length=10)),
                ("cust_name", models.CharField(max_length=40)),
                ("cust_email", models.CharField(max_length=40)),
                ("cust_address", models.CharField(max_length=120)),
                ("cust_password", models.CharField(max_length=20)),
                ("cust_temp", models.CharField(max_length=20)),
            ],
            options={"ordering": ["cust_mobile"],},
        ),
    ]
