# Generated by Django 4.2 on 2023-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0002_remove_customer_cust_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_mobile', models.CharField(max_length=10)),
                ('rest_name', models.CharField(max_length=10)),
                ('rest_addr', models.CharField(max_length=40)),
                ('rest_email', models.CharField(max_length=40)),
                ('rest_contact', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['rest_mobile'],
            },
        ),
    ]
