# Generated by Django 4.2 on 2023-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0003_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('rest_id', models.CharField(max_length=40)),
                ('item_name', models.CharField(max_length=40)),
                ('item_type', models.CharField(max_length=120)),
                ('item_price', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
    ]
