# Generated by Django 4.2 on 2023-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0005_remove_restaurantmenu_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='item_price',
            field=models.CharField(default=120, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='item_type',
            field=models.CharField(max_length=120),
        ),
    ]
