# Generated by Django 4.2 on 2023-04-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0006_restaurantmenu_item_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
