# Generated by Django 4.2 on 2023-04-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('rest_id', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=120)),
                ('order_date', models.CharField(max_length=20)),
                ('order_amount', models.CharField(max_length=20)),
                ('order_taxes', models.CharField(max_length=20)),
                ('order_net_amount', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_date', models.CharField(max_length=20)),
                ('payment_ref', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
