# Generated by Django 4.2 on 2023-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroApp', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=40)),
                ('item_quantity', models.CharField(max_length=40)),
                ('item_price', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
    ]
